# Generated by Django 3.2.9 on 2021-11-07 09:43

from django.db import migrations, models
import django.db.models.deletion
import regex_field.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegisteredImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image_path", models.URLField()),
                (
                    "invocation_validation_regex",
                    regex_field.fields.RegexField(default="", max_length=200),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Registered Images",
                "db_table": "registered_image",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("instance_uuid", models.UUIDField(default=uuid.uuid4)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "instance_type",
                    models.CharField(
                        choices=[
                            ("e2-micro", "E2_MICRO"),
                            ("e2-small", "E2_SMALL"),
                            ("e2-medium", "E2_MEDIUM"),
                        ],
                        max_length=30,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True)),
                ("finish_time", models.DateTimeField(blank=True)),
                ("disk_size_gb", models.PositiveIntegerField(default=10, max_length=100)),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("europe-west3-a", "EU_WEST_3A"),
                            ("europe-west3-b", "EU_WEST_3B"),
                            ("europe-west3-c", "EU_WEST_3C"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "PROCESSING"),
                            ("finished", "FINISHED"),
                            ("waiting", "WAITING"),
                            ("failed", "FAILED"),
                            ("aborted", "ABORTED"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                ("results", models.JSONField(blank=True, default=dict)),
                ("invocation_arguments", models.CharField(blank=True, max_length=500)),
                (
                    "imaged_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="job_lib.registeredimage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Jobs",
                "db_table": "job",
            },
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("status__in", ["processing", "finished", "waiting", "failed", "aborted"])
                ),
                name="job_status_valid",
            ),
        ),
    ]
