# Generated by Django 3.2.9 on 2021-11-07 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_lib", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="disk_size_gb",
            field=models.PositiveIntegerField(
                default=10,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
