# Generated by Django 3.2.9 on 2021-11-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_lib", "0002_alter_job_disk_size_gb"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="environment",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="registeredimage",
            name="tag",
            field=models.CharField(default="latest", max_length=100),
        ),
        migrations.AddField(
            model_name="registeredimage",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="registeredimage",
            name="image_path",
            field=models.CharField(max_length=200),
        ),
    ]
