# Generated by Django 3.2.9 on 2021-11-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_lib", "0003_auto_20211107_1147"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"verbose_name": "Job"},
        ),
        migrations.AlterModelOptions(
            name="registeredimage",
            options={"verbose_name": "Registered Image"},
        ),
        migrations.RenameField(
            model_name="job",
            old_name="imaged_id",
            new_name="image_id",
        ),
    ]
