# Generated by Django 3.2.9 on 2021-11-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_lib", "0004_auto_20211107_1156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="finish_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
