FROM python:3.10-slim
COPY ./dump_population_data_to_storage.py /app/dump_population_data_to_storage.py
COPY ./pubsub.py /app/pubsub.py

WORKDIR /app

RUN pip install google-cloud-storage requests click google-cloud-pubsub

RUN chmod +x /app/dump_population_data_to_storage.py

CMD ["bash", "-l"]
